version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - database

  database:
    image: sqlite:latest
    volumes:
      - ./data:/data
    command: sqlite3 /data/books.sqlite
