controllers:
    resource: '../src/Controller/'
    type: attribute

api_books_index:
    path: /books
    methods: [GET]
    controller: App\Controller\BookController::index

api_books_show:
    path: /books/{id}
    methods: [GET]
    controller: App\Controller\BookController::show

api_books_create:
    path: /books
    methods: [POST]
    controller: App\Controller\CreateBookController

api_books_update:
    path: /books/{id}
    methods: [PUT]
    controller: App\Controller\BookController::update

api_books_delete:
    path: /books/{id}
    methods: [DELETE]
    controller: App\Controller\BookController::delete

